accident_detection/urls.py
from django.contrib import admin
from django.urls import path

from detection_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home,name='home'),
    path("detect/", views.detect,name='detect'),
]

detection_app/models.py
from django.db import models

# Create your models here.

detection_app/forms.py
from django import forms

class UploadFileForm(forms.Form):
    video = forms.FileField()

detection_app/views.py
from django.shortcuts import render

from .forms import UploadFileForm
from detection_app.utils import handle_uploaded_file
# Create your views here.

def home(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            print("success")
            result = handle_uploaded_file(request.FILES["video"])
            # result = 'success'
            # return render(request,'result.html', {'result':result})

    else:
        form = UploadFileForm()
    return render(request,'home.html', {'form':form})
from .utils import startapplication


def detect(request):
    startapplication()
    return render(request,'home.html')

detection_app/templates/default.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><span class="navbar-brand mb-0 h1"><span>Detector</span></span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block page %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

detection_app/templates/home.html
{% extends "default.html" %} {% load static %} 
{% block page %}
<div class="container-fluid ">
    <div class="d-flex justify-content-around align-items-center " style="height: 90vh;">
        <div class="text-start  d-flex flex-column gap-2 col-6">
            <h1 id="heading">Accident <span>Detector</span></h1>
            <div id="input">
                <form method="post" enctype="multipart/form-data" class=" flex-column justify-content-center align-items-center">
                    {% csrf_token %}
                    <!-- {{ form.as_p }}   -->
                    <div class="form-group mb-3">
                        <input class="form-control" type="file" name="video" required id="id_video">
                    </div>
                    <button class="btn btn-secondary" type="submit" id="upload_btn">Upload</button>
                </form>
            </div>
            <div id="loading">
                <div class="loader m-auto"></div>
                <div class="loader_uploading m-auto"></div>
                <div class="loader_processing"></div>   
            </div>
        </div>
        
        <div class="d-flex flex-column justify-content-around align-items-center h-100 col-4" >
            <div class="camera container-fluid form-group p-5">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked>
                    <label class="form-check-label" for="flexRadioDefault1">
                      Camera 1
                      <p>
                        Address
                    </p>
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" >
                    <label class="form-check-label" for="flexRadioDefault2">
                        Camera 2
                        <p>
                            Address
                        </p>
                        
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" >
                    <label class="form-check-label" for="flexRadioDefault3">
                        Camera 3
                        <p>
                            Address
                        </p>
                    </label>
                  </div>
                  <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault4" >
                    <label class="form-check-label" for="flexRadioDefault4">
                        Camera 4
                        <p>
                            Address
                        </p>
                    </label>
                  </div>
            </div>
            
          
        </div>
        
    </div>
</div>
<script src="{% static 'jquery-3.7.1.js' %}"></script>
<script src="{% static 'Javascript/home.js' %}"></script>
{% endblock %}